name: bot

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Run bot
        env:
          GIST_TOKEN: ${{ secrents.GIST_TOKEN }}
          TWITTER_API_KEY: ${{ secrents.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrents.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrents.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrents.TWITTER_ACCESS_TOKEN_SECRET }} 
        run: npm start
