name: bot

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      with:
        version: 12.x
    
    - name: Install dependencies
      run: npm ci

    - name: Run bot
      run: node ./src/app.js
